name: My pipeline

onn:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: print present working directory
        run: pwd
      
      - name: print current user
        run: whoami

      - name: print system information
        run: uname -a

      - name: print current date and time
        run: date

      - name: print directory contents
        run: ls -la  
