name: Python CI

on:
  push:
    branches:
      - feature/jobs

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building"
     
  
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing"

  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying"